FROM balenalib/raspberrypi3-alpine-golang:1.11.2
WORKDIR /app
ADD . /app/
RUN echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing/" >> /etc/apk/repositories && \
    apk add --no-cache prometheus-node-exporter

CMD ["/app/entry.sh"]
